export const dummySuggestionData = {
  formId: "universal_form_001",
  fields: [
    {
      id: "first_name",
      name: "first_name",
      type: "text",
      label: "First Name",
      suggestedValue: "John",
    },
    {
      id: "middle_name",
      name: "middle_name",
      type: "text",
      label: "Middle Name",
      suggestedValue: "Alexander",
    },
    {
      id: "last_name",
      name: "last_name",
      type: "text",
      label: "Last Name",
      suggestedValue: "Doe",
    },
    {
      id: "full_name",
      name: "full_name",
      type: "text",
      label: "Full Name",
      suggestedValue: "John Alexander Doe",
    },
    {
      id: "preferred_username",
      name: "username",
      type: "text",
      label: "Username",
      suggestedValue: "john_alex",
    },
    {
      id: "email",
      name: "email",
      type: "email",
      label: "Email Address",
      suggestedValue: "john.doe@example.com",
    },
    {
      id: "alt_email",
      name: "alt_email",
      type: "email",
      label: "Alternate Email",
      suggestedValue: "contact.johndoe@example.com",
    },
    {
      id: "phone_number",
      name: "phone",
      type: "tel",
      label: "Mobile Phone",
      suggestedValue: "+1 555 234 5678",
    },
    {
      id: "alt_phone",
      name: "alt_phone",
      type: "tel",
      label: "Alternate Phone",
      suggestedValue: "+1 555 987 6543",
    },
    {
      id: "dob",
      name: "dob",
      type: "date",
      label: "Date of Birth",
      suggestedValue: "1990-07-15",
    },
    {
      id: "gender",
      name: "gender",
      type: "radio",
      label: "Gender",
      suggestedValue: "male",
    },
    {
      id: "marital_status",
      name: "marital_status",
      type: "select",
      label: "Marital Status",
      suggestedValue: "Single",
    },
    {
      id: "nationality",
      name: "nationality",
      type: "select",
      label: "Nationality",
      suggestedValue: "United States",
    },
    {
      id: "address_line1",
      name: "address1",
      type: "text",
      label: "Address Line 1",
      suggestedValue: "742 Evergreen Terrace",
    },
    {
      id: "address_line2",
      name: "address2",
      type: "text",
      label: "Address Line 2",
      suggestedValue: "Unit 5B",
    },
    {
      id: "city",
      name: "city",
      type: "text",
      label: "City",
      suggestedValue: "Springfield",
    },
    {
      id: "state",
      name: "state",
      type: "select",
      label: "State / Province",
      suggestedValue: "Illinois",
    },
    {
      id: "country",
      name: "country",
      type: "select",
      label: "Country",
      suggestedValue: "United States",
    },
    {
      id: "postal_code",
      name: "postal_code",
      type: "text",
      label: "Postal Code",
      suggestedValue: "62704",
    },
    {
      id: "company_name",
      name: "company_name",
      type: "text",
      label: "Company Name",
      suggestedValue: "Acme Corporation",
    },
    {
      id: "job_title",
      name: "job_title",
      type: "text",
      label: "Job Title",
      suggestedValue: "Software Engineer",
    },
    {
      id: "website",
      name: "website",
      type: "url",
      label: "Website",
      suggestedValue: "https://www.johndoe.dev",
    },
    {
      id: "linkedin",
      name: "linkedin",
      type: "url",
      label: "LinkedIn Profile",
      suggestedValue: "https://www.linkedin.com/in/johndoe",
    },
    {
      id: "password",
      name: "password",
      type: "password",
      label: "Password",
      suggestedValue: "TestPass@2024",
    },
    {
      id: "confirm_password",
      name: "confirm_password",
      type: "password",
      label: "Confirm Password",
      suggestedValue: "TestPass@2024",
    },
    {
      id: "credit_card_number",
      name: "card_number",
      type: "text",
      label: "Credit Card Number",
      suggestedValue: "4111 1111 1111 1111",
    },
    {
      id: "expiry_date",
      name: "expiry_date",
      type: "month",
      label: "Expiry Date",
      suggestedValue: "2026-08",
    },
    {
      id: "cvv",
      name: "cvv",
      type: "password",
      label: "CVV",
      suggestedValue: "123",
    },
    {
      id: "agree_terms",
      name: "agree_terms",
      type: "checkbox",
      label: "I agree to the terms and conditions",
      suggestedValue: "true",
    },
    {
      id: "newsletter_opt_in",
      name: "newsletter",
      type: "checkbox",
      label: "Subscribe to Newsletter",
      suggestedValue: "true",
    },
    {
      id: "comments",
      name: "comments",
      type: "textarea",
      label: "Additional Comments",
      suggestedValue: "Looking forward to using your service.",
    },
  ],
};
